name: Merge dev to main

on:
    push:
        branches: ["dev"]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Push to main
              run: git push origin/main
