name: Merge dev

on:
    push:
        branches: ["dev"]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    merge-dev:
        name: "Merge dev"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Push to main
              run: |
                  git config --global user.name 'Andrew Richardson'
                  git config --global user.email 'andrewRichardson@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git push origin main
