name: status-checks
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test suite
        runs_on: ubuntu-latest
        steps:
            - name: Check out repository
              - uses: actions/checkout@v3
            - name: Setup node
              - uses: actions/setup-node@v3
                with:
                  node-version: '18'
            - name: Install node modules
              run: yarn install
            - name: Run test suite
              run: yarn test
