name: status-checks
on:
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test suite
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install node modules
              run: yarn install
            - name: Run test suite
              run: yarn test
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install node modules
              run: yarn install
            - name: Build app
              run: yarn build
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install node modules
              run: yarn install
            - name: Lint app
              run: yarn lint
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install node modules
              run: yarn install
            - name: Format app
              run: yarn format
